In [197]:
import pandas as pd, math, numpy as np, matplotlib.pyplot as plt, seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.naive_bayes import GaussianNB

## Importação e tratamento dos dados

In [114]:

path = r'C:\Users\Davi\Documents\Projetos\FIAP\FASE 4\Cap3\documents\seeds_dataset.txt'

df = pd.read_csv(r"C:\Users\Davi\Documents\Projetos\FIAP\FASE 4\Cap3\documents\seeds_dataset.txt", sep='\s+')
df.columns = ['AREA', 'PERIMETRO', 'COMPACIDADE', 'COMPRIMENTO DO NUCLEO', 'LARGURA DO NUCLEO', 'COEFICIENTE DE ASSIMETRIA', 'COMPRIMENTO DO SULCO DO NUCLEO', 'AMOSTRA']

df['AMOSTRA'] = df['AMOSTRA'].map({1:'Kama', 2:'Rosa', 3:'Canadian'})

## Identificação e tratativa de valorez vaizos
for col in df.columns:
    for a in df[col].isna():
        if a == True:
            print({col:a})
            df = df.fillna({col:0.0})


display(df)

AREA  PERIMETRO  COMPACIDADE  COMPRIMENTO DO NUCLEO  LARGURA DO NUCLEO  \
0    14.88      14.57       0.8811                  5.554              3.333   
1    14.29      14.09       0.9050                  5.291              3.337   
2    13.84      13.94       0.8955                  5.324              3.379   
3    16.14      14.99       0.9034                  5.658              3.562   
4    14.38      14.21       0.8951                  5.386              3.312   
..     ...        ...          ...                    ...                ...   
204  12.19      13.20       0.8783                  5.137              2.981   
205  11.23      12.88       0.8511                  5.140              2.795   
206  13.20      13.66       0.8883                  5.236              3.232   
207  11.84      13.21       0.8521                  5.175              2.836   
208  12.30      13.34       0.8684                  5.243              2.974   

     COEFICIENTE DE ASSIMETRIA  COMPRIMENTO DO SULCO DO NUCLEO   AMOSTRA  
0                        1.018                           4.956      Kama  
1                        2.699                           4.825      Kama  
2                        2.259                           4.805      Kama  
3                        1.355                           5.175      Kama  
4                        2.462                           4.956      Kama  
..                         ...                             ...       ...  
204                      3.631                           4.870  Canadian  
205                      4.325                           5.003  Canadian  
206                      8.315                           5.056  Canadian  
207                      3.598                           5.044  Canadian  
208                      5.637                           5.063  Canadian  

[209 rows x 8 columns]

## Definindo media


In [ ]:
media = {
    'AREA':[], 
    'PERIMETRO':[], 
    'COMPACIDADE':[], 
    'COMPRIMENTO DO NUCLEO':[], 
    'LARGURA DO NUCLEO':[], 
    'COEFICIENTE DE ASSIMETRIA':[], 
    'COMPRIMENTO DO SULCO DO NUCLEO':[], 
    'AMOSTRA':['Kama', 'Rosa', 'Canadian']
    }
# media['AREA'] = float(df.loc[df['AMOSTRA'] == 1, 'AREA'].mean())
media['AREA'] = [float(df.loc[df['AMOSTRA'] == a, 'AREA'].mean()) for a in range(1, 4)]
media['PERIMETRO'] = [float(df.loc[df['AMOSTRA'] == a, 'PERIMETRO'].mean()) for a in range(1, 4)]
media['COMPACIDADE'] = [float(df.loc[df['AMOSTRA'] == a, 'COMPACIDADE'].mean()) for a in range(1, 4)]
media['COMPRIMENTO DO NUCLEO'] = [float(df.loc[df['AMOSTRA'] == a, 'COMPRIMENTO DO NUCLEO'].mean()) for a in range(1, 4)]
media['LARGURA DO NUCLEO'] = [float(df.loc[df['AMOSTRA'] == a, 'LARGURA DO NUCLEO'].mean()) for a in range(1, 4)]
media['COEFICIENTE DE ASSIMETRIA'] = [float(df.loc[df['AMOSTRA'] == a, 'COEFICIENTE DE ASSIMETRIA'].mean()) for a in range(1, 4)]
media['COMPRIMENTO DO SULCO DO NUCLEO'] = [float(df.loc[df['AMOSTRA'] == a, 'COMPRIMENTO DO SULCO DO NUCLEO'].mean()) for a in range(1, 4)]
# del m
print(media)

## Definindo mediana

In [ ]:
mediana = {
    'AREA':[], 
    'PERIMETRO':[], 
    'COMPACIDADE':[], 
    'COMPRIMENTO DO NUCLEO':[], 
    'LARGURA DO NUCLEO':[], 
    'COEFICIENTE DE ASSIMETRIA':[], 
    'COMPRIMENTO DO SULCO DO NUCLEO':[], 
    'AMOSTRA':['Kama', 'Rosa', 'Canadian']
    }

mediana['AREA'] = [float(df.loc[df['AMOSTRA'] == a, 'AREA'].median()) for a in range(1, 4)]
mediana['PERIMETRO'] = [float(df.loc[df['AMOSTRA'] == a, 'PERIMETRO'].median()) for a in range(1, 4)]
mediana['COMPACIDADE'] = [float(df.loc[df['AMOSTRA'] == a, 'COMPACIDADE'].median()) for a in range(1, 4)]
mediana['COMPRIMENTO DO NUCLEO'] = [float(df.loc[df['AMOSTRA'] == a, 'COMPRIMENTO DO NUCLEO'].median()) for a in range(1, 4)]
mediana['LARGURA DO NUCLEO'] = [float(df.loc[df['AMOSTRA'] == a, 'LARGURA DO NUCLEO'].median()) for a in range(1, 4)]
mediana['COEFICIENTE DE ASSIMETRIA'] = [float(df.loc[df['AMOSTRA'] == a, 'COEFICIENTE DE ASSIMETRIA'].median()) for a in range(1, 4)]
mediana['COMPRIMENTO DO SULCO DO NUCLEO'] = [float(df.loc[df['AMOSTRA'] == a, 'COMPRIMENTO DO SULCO DO NUCLEO'].median()) for a in range(1, 4)]

print(mediana)

## Definindo desvio padrão

In [ ]:
mediana = {
    'AREA':[], 
    'PERIMETRO':[], 
    'COMPACIDADE':[], 
    'COMPRIMENTO DO NUCLEO':[], 
    'LARGURA DO NUCLEO':[], 
    'COEFICIENTE DE ASSIMETRIA':[], 
    'COMPRIMENTO DO SULCO DO NUCLEO':[], 
    'AMOSTRA':['Kama', 'Rosa', 'Canadian']
    }

mediana['AREA'] = [float(df.loc[df['AMOSTRA'] == a, 'AREA'].std()) for a in range(1, 4)]
mediana['PERIMETRO'] = [float(df.loc[df['AMOSTRA'] == a, 'PERIMETRO'].std()) for a in range(1, 4)]
mediana['COMPACIDADE'] = [float(df.loc[df['AMOSTRA'] == a, 'COMPACIDADE'].std()) for a in range(1, 4)]
mediana['COMPRIMENTO DO NUCLEO'] = [float(df.loc[df['AMOSTRA'] == a, 'COMPRIMENTO DO NUCLEO'].std()) for a in range(1, 4)]
mediana['LARGURA DO NUCLEO'] = [float(df.loc[df['AMOSTRA'] == a, 'LARGURA DO NUCLEO'].std()) for a in range(1, 4)]
mediana['COEFICIENTE DE ASSIMETRIA'] = [float(df.loc[df['AMOSTRA'] == a, 'COEFICIENTE DE ASSIMETRIA'].std()) for a in range(1, 4)]
mediana['COMPRIMENTO DO SULCO DO NUCLEO'] = [float(df.loc[df['AMOSTRA'] == a, 'COMPRIMENTO DO SULCO DO NUCLEO'].std()) for a in range(1, 4)]

print(mediana)

## Boxplot

In [ ]:
for col in df.columns:
    if col != 'AMOSTRA':
        plt.figure(figsize=(10,4))
        sns.boxplot(x=df['AMOSTRA'], y=df[col])
        plt.suptitle('Distribuição das Características - BOXPLOT', fontsize=16)
        plt.tight_layout()
        plt.show()

## Histograma

In [ ]:
for col in df.columns:
    if col != 'AMOSTRA':
        plt.figure(figsize=(10,4))
        sns.histplot(x=df['AMOSTRA'], y=df[col])
        plt.suptitle('Distribuição das Características - Histograma', fontsize=16)
        plt.tight_layout()
        plt.show()

## Dispersão de caracteristicas

### AREA x PERIMETRO

In [ ]:
plt.figure(figsize=(7, 5))
sns.scatterplot(data=df, x='AREA', y='PERIMETRO', hue='AMOSTRA', palette='Set1')
plt.title('Área vs Perimetro - Classificação dos Grãos')
plt.xlabel('Área')
plt.ylabel('Perimetro')
plt.grid(True)
plt.show()

### AREA X COMPRIMENTO DO NUCLEO

In [ ]:
plt.figure(figsize=(7, 5))
sns.scatterplot(data=df, x='AREA', y='COMPRIMENTO DO NUCLEO', hue='AMOSTRA', palette='Set1')
plt.title('Área vs Comprimento do Nucleo - Classificação dos Grãos')
plt.xlabel('Área')
plt.ylabel('Comprimento do Nucleo')
plt.grid(True)
plt.show()

### COEFICIENTE DE ASSIMETRIA X COMPRIMENTO DO NUCLEO

In [ ]:
plt.figure(figsize=(7, 5))
sns.scatterplot(data=df, x='COEFICIENTE DE ASSIMETRIA', y='COMPRIMENTO DO NUCLEO', hue='AMOSTRA', palette='Set1')
plt.title('Coeficiente de Assimetria vs Comprimento do Nucleo - Classificação dos Grãos')
plt.xlabel('Coeficiente de Assimetria')
plt.ylabel('Comprimento do Nucleo')
plt.grid(True)
plt.show()

## Separação de conjuntos de treino e teste

In [164]:
x_test, x_train, y_test, y_train = train_test_split(df[['AREA', 'PERIMETRO', 'COMPACIDADE', 'COMPRIMENTO DO NUCLEO', 'LARGURA DO NUCLEO', 'COEFICIENTE DE ASSIMETRIA', 'COMPRIMENTO DO SULCO DO NUCLEO']], df['AMOSTRA'], train_size=0.3, random_state=30)
print(f'COMPRIMENTO MODELO DE TREINO (X): {len(x_train)}')
print(f'COMPRIMENTO MODELO DE TESTE (X): {len(x_test)}')
print(f'COMPRIMENTO MODELO DE TREINO (y): {len(y_train)}')
print(f'COMPRIMENTO MODELO DE TESTE (y): {len(y_test)}')

COMPRIMENTO MODELO DE TREINO (X): 147
COMPRIMENTO MODELO DE TESTE (X): 62
COMPRIMENTO MODELO DE TREINO (y): 147
COMPRIMENTO MODELO DE TESTE (y): 62



## Treinamento dos modelos

### RandomForestClassifier

In [193]:
ml_rf = RandomForestClassifier()
ml_rf.fit(X=x_train, y=y_train)

RandomForestClassifier()

In [196]:
rf_predict = ml_rf.predict(x_test)
print(classification_report(y_test, rf_predict))
# del test

              precision    recall  f1-score   support

    Canadian       0.88      0.96      0.92        23
        Kama       0.90      0.83      0.86        23
        Rosa       0.94      0.94      0.94        16

    accuracy                           0.90        62
   macro avg       0.91      0.91      0.91        62
weighted avg       0.90      0.90      0.90        62



### SVM

In [186]:
ml_scaler = StandardScaler()
x_scaler = ml_scaler.fit_transform(x_train)
df_scaled = pd.DataFrame(x_scaler, columns=['AREA', 'PERIMETRO', 'COMPACIDADE', 'COMPRIMENTO DO NUCLEO', 'LARGURA DO NUCLEO', 'COEFICIENTE DE ASSIMETRIA', 'COMPRIMENTO DO SULCO DO NUCLEO'])
ml_svm = SVC()
ml_svm.fit(x_train, y_train)



SVC()

In [ ]:
y_pred = ml_svm.predict(x_test)

print("Matriz de Confusão:")
print(confusion_matrix(y_test, y_pred))

print("\nRelatório de Classificação:")
print(classification_report(y_test, y_pred))

array(['Kama', 'Kama', 'Kama', 'Kama', 'Kama', 'Kama', 'Kama', 'Canadian',
       'Canadian', 'Rosa', 'Rosa', 'Canadian', 'Canadian', 'Kama', 'Rosa',
       'Canadian', 'Kama', 'Kama', 'Rosa', 'Rosa', 'Rosa', 'Rosa', 'Rosa',
       'Rosa', 'Canadian', 'Kama', 'Canadian', 'Kama', 'Canadian',
       'Canadian', 'Kama', 'Canadian', 'Kama', 'Canadian', 'Kama', 'Kama',
       'Canadian', 'Kama', 'Canadian', 'Rosa', 'Rosa', 'Canadian',
       'Canadian', 'Canadian', 'Canadian', 'Canadian', 'Canadian', 'Kama',
       'Rosa', 'Rosa', 'Canadian', 'Kama', 'Canadian', 'Canadian', 'Kama',
       'Rosa', 'Canadian', 'Canadian', 'Kama', 'Canadian', 'Canadian',
       'Kama'], dtype=object)

Matriz de Confusão:
[[23  0  0]
 [ 3 19  1]
 [ 0  3 13]]

Relatório de Classificação:
              precision    recall  f1-score   support

    Canadian       0.88      1.00      0.94        23
        Kama       0.86      0.83      0.84        23
        Rosa       0.93      0.81      0.87        16

    accuracy                           0.89        62
   macro avg       0.89      0.88      0.88        62
weighted avg       0.89      0.89      0.89        62



### Native Bayes

In [ ]:
ml_bayes = GaussianNB()
ml_bayes.fit(x_train, y_train)

GaussianNB()

In [203]:
bayes_predict = ml_bayes.predict(x_test)
print("\nRelatório de Classificação:")
print(classification_report(y_test, bayes_predict))


Relatório de Classificação:
              precision    recall  f1-score   support

    Canadian       0.92      0.96      0.94        23
        Kama       0.83      0.87      0.85        23
        Rosa       0.93      0.81      0.87        16

    accuracy                           0.89        62
   macro avg       0.89      0.88      0.88        62
weighted avg       0.89      0.89      0.89        62

